language: node_js
node_js: stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower karma grunt-cli jshint
- npm install
- bower install
env:
  global:
    - secure: Ap09dnlh81UrEDZvi3KKKeD1LxHl2bGEAQmHyY3eJhAnSyk5dGMe9lJyfAmggOL5MmB2NGwEnoS6+KJjwHFUDezXucdvNNBbavhUMJoOH5TvF0oxLv06yvMXPVLPUMDUqWWMihJSs/XVqcRbPreQ+X01rWDHKULfOdXcHqRaKo0AORPkl0CjB+Nkpww7FS0y2DjlDWJGadisk0KEcBgkDBdcRurUIqFp5CETS8CGauEYeXYnmuS+yt0t+cVTEyebex2Q6oNuz9stG7NcBcsG52M+kEk7978Pxzxo/sBD/5l2510rIbezhFnMxA3zmBXVaF7xVp1s7mJMu03pEMik6SNKqjEJOfh9zSKSS6r+HemO9PlfuWVQrPTSNQTTCQS+ir9NVJ65a9Kz2iTis03n7p0rAEdXprmWxYeYnrivirRcgnjsS6akiEiOUk9VQSmYYnXsihdHV7vp/S8RvKIw5tBctDKWAAPbiLVT/jANI0y+Z/fm5/VkjgZWkhokuMEkc9Y959+gefmFAoH4pRHJVjg0KzPF81+sDeMuY7X8iOYFCgwfLdX3saW//9QrzJ3MCM4Pjp/pgQXWyxHfqYKEDxxubdYlLi2YzMI8rta8bi538Il9GWTbEvAyw3Oy6G/gVHSfKyBBnMM5FA361uP/bS/404F5NYQBpH9LTHhtHTo=
    - secure: RxhrzEP3LMJcAu4i50+DGQpaG1SBAN1jPpRFXM5JX7D04fpuufkhqtuUENtPyNRQSEk5CcILyVXaG/C/5BuAAPU+7fllJARCw2N39cHiVST+qrsykqcDv0qdK7sI9GA7fnQCt+zxg/rtcQoptXnnSyAhgWD+ZNLdC+bB/lLu94DTpLkm8Pcc4eMafPykFOFGjnlRMhno/NSfHLQrRFhWv8dQh6rzdoESdeESba8CeGo0pKOUyn89vC/AuAc4e47vDxvQKl/McpJ+sEvTudeRrI5lIMbAHuHVEBIWM2WN7dtfcwNFVutJi1do23grymF+rtD4wsx50SS7RMvCFt+a7X3CSWniwPDQzvRVQtf4gafmEUeVzxsPfh/YAcXih9KHVmWDmDDUs4JiTgC7X9gzEj9q8uygDeqrRdhVmCI/CUYoQnuSA5rC+uDKJdvjJrf22iCCL37Ksfrmx8Bvcj6GJfO/AzvZHDFI5nRzNaN6QJYtCTmBpqakWXdR8m0PjgVXQnYbRt44qla2s/9CRkgbCR0IxABQnpcSt7UUe62I0dEXNZarCk9Yfb6IGqBk9Ca5cg2KasqD3BwrYvqQT8F8kA/nKaiFWttQwd7HqqNDAAhiZybg2xPR4Rtc2d4rz+W50zskYJmMbJ9Q5orbiuy2jNOtrs56X6AR3V+1vem5B/I=
addons:
  sauce_connect: true