language: node_js
node_js: stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower karma grunt-cli jshint
- npm install
- bower install
addons:
  sauce_connect: true
env:
  global:
  - secure: JKElvoqp3bFrUqyqLyjT6glVFpdsKSqi4HiWVmMNnMka58C1FBHeUvfHm7wF21Hg5DfLHgI74v2sV0FFv3izFopRuXe2DHC+XyBXFFcJADHBmBmxryX8lUnK/3HLELm/lUyy3Yl+JlDjEBMxly7cjltMZ2xwjM6HlqNOE0wY0qr+7aqW6PAPfl21kCXCOl0Kx3jN19Z64XNxcUj290jjlGx937T60QAvLqHeyVb2QLPhYjQh7jw588sSZt8kqHqUYbqjR7C5p7N2skOGlvAiU8IOildB12X018us2+z9wUdqbtCcNMkmT7Ogi2v/yhi4jel63JNDPnTIOuVTEznjDwhfpmQWqdAcU57VbhNqsl8baxM+fK8tLwtAT07NAWq59nfTdDFxmglWYwuAs84q4xdPvWBZA67fDGKMSLqGMSVXpInuSStN7SXH5GTTOivTdQyn6yTVuWc4KNVcK5n2ezrE6jRBY9wxz2NinEs1ahKVZPMoWVUifDCvLzM12qwIcDTWUuB/C6OijRJWr/yNfzCFpQ3z/mS4BzntOi/Hw584GKqEutniVYpnC+3v4vj5534fsEtKO5GkVOIOZGo6uThzjjDhK9bDHVFS0W2gy/pco93+0HI+jZ2UfA4z/SVS+5tm/juygEsu9bird2a8h/603yGz21TmpIzxLTL01RQ=
  - secure: JT1bkhIr8R4sBtzxXBmpGdND8qgkNf7kxXjthygkW+Oo7qdFj1KM6lTd7WU13oktfIoJxWgIAoNlGVH+CJZuFWVDJIv1cnl38MV8EuPofiKH7vVhlzVzo4JONwqchNLr0jNzcs0QUU0rCqKCqfv7xvvG59CWU5VhdpG74ej6xTSG1/biWxDCx21/six0QkP4NBZckwq+ZbRdVb664ddk8ve4aWcQn/guYzivrr7SWb/+/2mUmrDpqA1cEhpeVdqYU9VNBU3I7OtIUbszStUai/P8YkQoslzDmHCKVgKsfefjuvYS6rz7nxaHrGd26qEMNVbu++a97ubhlqyHA75vPwxRK9J1Fm/M9QC6jLoINwQDOBG6PtW908KrwHn0ELfPqPAj19wFtmWbLr0iZ3w4d4IzCvEZxmvFSjbw3ZQqYEwRCAu7AL1nGIw3pYeJuxzV54L+N6Jmv3ViYVhikvT8LDXkc4WRjjhYfRpstuBK5AKJfXarA6CRU3rGmfJ/XxlxRsKUvvjf6CnWrCTx9WcVj0x+uw++5JFeot9zpq7n17NthZ58D+PqClcGn9wZcPcyxr2cbdcr9/R5tlieHOQ9vxUvb8BbHEtcaXcbluuai76Ifx1JkgpWkyruQii9JOgzH2Gft3+H9R2Lg3tbnPLsIjPEP8+eX9CNLbsqIsBr0LQ=
