language: node_js
node_js: stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower karma grunt-cli jshint
- npm install
- bower install
env:
  global:
  - secure: f9dXAGfWUxhbvDM0HqiWe1QYvOnZU8SBnZbPBypVjkb2GE2VimWtKQ+oYmszU850mFeUUwoDrB55uwS2FYUcwt9+xHux9SL8ZVbyO/J9maknaFull5Qut88FBWtQKUb4CzUqTDcFQT9x74ZgqMV+wHGML6RfH60QN7Ao63Ym/2U3wLHIsWPjd6vlR2oQToFh6x88fVTe5Xr3Lpi9jLdj39iyVzFTfIA492BC8fYzPGsWK5W0QMgRuLcM6WMV2yblBO93Kh5NZ6eXAbgm2diK8mm6Fov9eKLQtiOQ8E5W8WAn9bQzlSScvXHuxVBqIcWw1D5OXp94dMFN/WE18anebijOn1xoezVVHnrlw7iPmnSEPzLG8anY7RYjfS9JrfQDcF5L2lvLqr7KmXyn+zBhRud5KoM4O3GeMFeBceqRjRaU9JzMCbMn5h9csfAEJyd/JZ4A4YCvrFC/jnfIonY66PcQyQslKquKLvOVoSbPKNa1/wrnYbfXCgmDI60Zqjy8ZHHTXoWsY8hHnq0H9Ev7nPPY1UilaJeahoTUcx94pRjrvWfS6Lu/8tmTLjAyeOsZkBwJPzW6SLrJ0404XHs3mNkuryO6q+k7Xp9Z/X1fYsNfYA6Ll7hXY8j2oF7TV/UfAc54z6wuiOEs6NrRuIN1rg/Tlmk4wRT1zHjQCDWIfg0=
  - secure: ByG86DhBUzV0LiWm+yzXL8dyFjOeMd0cpTkcE6dzH9VuwMGXLLgtj+WyNXOujkpnzbGeURQJ8M1MxvJKcf36m1OVtOd6/2N2iKfaY5moDDwHcuShttC6IJc6uVRCwCQOYp5iBb/8Jg+LUuITDJMeUEXzEJAf30LQjd40TWlno1D+YS2DHJUARxbV6NyKxMzJA6uV7oa7CLvyHQYJSu3O0DsgTbGwhiPaKOnEFgaI4FyRs0I3Es6RZi8xBo0Grp3hZ8p3enSnMwB8CQKMD9/gxjcdV4h2R6YLfQ/PDgnBZShqMeTvlJ6TVqtvohlcpuxjsAr/NffdRTfleIDziga8G9EujAp1WeMS2eHnlMjdpAevwOkq61gY1dCR0SfKqcpG4D1YmWhdJmtPd5DC2Lu3P44fg0ISWC4DEPHc0ukQ+zhlah9clJypBqf0BSSp5eGzQcWoGpZdWWSWA/tpuZ7WficrW4EBHd6BBaMFhJbNna9qLEL+BPxRwcagCykgOqZQavWoyxoL742FUOuEqp7XCLZ49NbmkHga9m/ufs8tNWV7TOLAX2Y1CJjh+HricX+mTCybFGELHlB8KyzRQIRT8pwb2ZUTxKz8hj/bD/eJ6B8jIkLpaTPxxxWoJ+PPBjkM4bl0Legarcdo/MPiTD1WUH5QfeqMDVnqMXNQso5XXSI=
addons:
  sauce_connect: true